services:
  mysql_db:
    image: mysql:8.4
    container_name: mysql_db
    restart: always
    env_file:
      - .env
    volumes:
      - $HOME/template_DB/database:/var/lib/mysql
      - ./schema.sql:/docker-entrypoint-initdb.d/0_init.sql
    ports:
      - 3306:3306
    expose:
      - 3306
